# Generated by Django 4.1 on 2023-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskscheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="availability_end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="availability_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterModelTable(
            name="project",
            table="project",
        ),
        migrations.AlterModelTable(
            name="resource",
            table="resource",
        ),
        migrations.AlterModelTable(
            name="skill",
            table="skill",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task",
        ),
    ]
