# Generated by Django 4.1 on 2023-07-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taskscheduler",
            "0003_project_completed_task_completed_task_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_date",
            field=models.DateField(null=True),
        ),
    ]
