# Generated by Django 4.1 on 2023-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskscheduler", "0004_task_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completed_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_date",
            field=models.DateField(null=True),
        ),
    ]
