# Generated by Django 4.1 on 2023-07-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskscheduler", "0005_project_completed_date_task_completed_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="man_days",
        ),
        migrations.AddField(
            model_name="task",
            name="estimation",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="availability_start_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
