# Generated by Django 4.2.3 on 2023-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskscheduler", "0007_assignments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignments",
            name="completed",
        ),
        migrations.AlterField(
            model_name="assignments",
            name="status",
            field=models.CharField(
                choices=[("ASSIGNED", "Assigned"), ("COMPLETED", "Completed")],
                max_length=10,
            ),
        ),
    ]
