# Generated by Django 4.0 on 2023-07-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskscheduler", "0008_remove_assignments_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="skills",
            field=models.ManyToManyField(to="taskscheduler.Skill"),
        ),
        migrations.AlterField(
            model_name="task",
            name="skills_required",
            field=models.ManyToManyField(to="taskscheduler.Skill"),
        ),
    ]
